# 版本 时间戳
version: 1697095219302

# 地址信息
address: 
  Torn:
    # 合约地址
    contract_address: TFMCyqPYQQvTc7PGEWhQdXy3uwwAs3dYBx
    # 财务人员
    wallet_address: ["TCXJJvq1F8YHN5uXs4UhTUmN8RFUxs2Zd2"]
    # 谷歌验证码
    google_auth_key: WUZYEKZWDODIFUU3