name: Greeting from Mona
on: push

jobs:
  my-job:
    name: My Job
    runs-on: windows-latest
    steps:
    - name: Print a greeting
      uses: actions/checkout@main
      env:
        MY_VAR: Hi there! My name is
        FIRST_NAME: Mona
        MIDDLE_NAME: The
        LAST_NAME: Octocat
      run: |
        # choco install python -y
        python -V
        pip -V
        pip install fastapi uvicorn
        pip install pyinstaller
        pyinstaller -F test.py
        echo $MY_VAR $FIRST_NAME $MIDDLE_NAME $LAST_NAME.
