name: Greeting from Mona
on: push

env:
  # 生成windows执行程序
  PACK_WINDOWS : false
  # 生成mac执行程序
  PACK_MAC : true

jobs:
  # 生成windows执行程序
  pack_windows_job:
    if: $PACK_WINDOWS == 'true'
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: pyinstaller-exe
      run: |
        # choco install python -y
        python -V
        pip -V
        pip install fastapi uvicorn
        pip install pyinstaller
        pyinstaller -F test.py
        ls
  
  # 生成mac执行程序
  pack_mac_job:
    if: $PACK_MAC == 'true'
    runs-on: macOS-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: pyinstaller
      run: |
        # choco install python -y
        python -V
        pip -V
        pip install fastapi uvicorn
        pip install pyinstaller
        pyinstaller -F test.py
        ls
    
